eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
ribbon:
  eureka:
    enabled: true
