spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.58.234:3306/z151?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      idle-timeout: 600000  #10 min
      max-lifetime: 1800000 #30 min
  application:
    name: dbConnector
  profiles:
    active: dev

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: repository.

#logging logback
logging:
  config: classpath:logback-spring.xml
  file:
    name: eraytDbConnector