spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.58.234:3306/z151?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      idle-timeout: 600000  #10 min
      max-lifetime: 1800000 #30 min
  application:
    name: single
  profiles:
    active:  dev

  thymeleaf:
    cache: false
    encoding: UTF-8
server:
  port: 8087

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: repository.

#logging logback
logging:
  file:
    path: ./single/
    name: single1
  config: classpath:logback-spring.xml

# 系统相关，
erayt:
  demo:
    userName: visit
    password: 123456
  system:
    tokenType: 1   #:2:启动header 中的token校验。